// GENERATED by `dart run ffigen` from <linux/gpio.h>. Do not edit by hand.
// ignore_for_file: type=lint, unused_field, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

typedef __u32 = ffi.UnsignedInt;
typedef Dart__u32 = int;

/// struct gpiochip_info - Information about a certain GPIO chip
/// @name: the Linux kernel name of this GPIO chip
/// @label: a functional name for this GPIO chip, such as a product
/// number, may be empty (i.e. label[0] == '\0')
/// @lines: number of GPIO lines on this chip
final class gpiochip_info extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> name;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> label;

  @__u32()
  external int lines;
}

/// enum gpio_v2_line_flag - &struct gpio_v2_line_attribute.flags values
/// @GPIO_V2_LINE_FLAG_USED: line is not available for request
/// @GPIO_V2_LINE_FLAG_ACTIVE_LOW: line active state is physical low
/// @GPIO_V2_LINE_FLAG_INPUT: line is an input
/// @GPIO_V2_LINE_FLAG_OUTPUT: line is an output
/// @GPIO_V2_LINE_FLAG_EDGE_RISING: line detects rising (inactive to active)
/// edges
/// @GPIO_V2_LINE_FLAG_EDGE_FALLING: line detects falling (active to
/// inactive) edges
/// @GPIO_V2_LINE_FLAG_OPEN_DRAIN: line is an open drain output
/// @GPIO_V2_LINE_FLAG_OPEN_SOURCE: line is an open source output
/// @GPIO_V2_LINE_FLAG_BIAS_PULL_UP: line has pull-up bias enabled
/// @GPIO_V2_LINE_FLAG_BIAS_PULL_DOWN: line has pull-down bias enabled
/// @GPIO_V2_LINE_FLAG_BIAS_DISABLED: line has bias disabled
/// @GPIO_V2_LINE_FLAG_EVENT_CLOCK_REALTIME: line events contain REALTIME timestamps
/// @GPIO_V2_LINE_FLAG_EVENT_CLOCK_HTE: line events contain timestamps from
/// hardware timestamp engine
enum gpio_v2_line_flag {
  GPIO_V2_LINE_FLAG_USED(1),
  GPIO_V2_LINE_FLAG_ACTIVE_LOW(2),
  GPIO_V2_LINE_FLAG_INPUT(4),
  GPIO_V2_LINE_FLAG_OUTPUT(8),
  GPIO_V2_LINE_FLAG_EDGE_RISING(16),
  GPIO_V2_LINE_FLAG_EDGE_FALLING(32),
  GPIO_V2_LINE_FLAG_OPEN_DRAIN(64),
  GPIO_V2_LINE_FLAG_OPEN_SOURCE(128),
  GPIO_V2_LINE_FLAG_BIAS_PULL_UP(256),
  GPIO_V2_LINE_FLAG_BIAS_PULL_DOWN(512),
  GPIO_V2_LINE_FLAG_BIAS_DISABLED(1024),
  GPIO_V2_LINE_FLAG_EVENT_CLOCK_REALTIME(2048),
  GPIO_V2_LINE_FLAG_EVENT_CLOCK_HTE(4096);

  final int value;
  const gpio_v2_line_flag(this.value);

  static gpio_v2_line_flag fromValue(int value) => switch (value) {
        1 => GPIO_V2_LINE_FLAG_USED,
        2 => GPIO_V2_LINE_FLAG_ACTIVE_LOW,
        4 => GPIO_V2_LINE_FLAG_INPUT,
        8 => GPIO_V2_LINE_FLAG_OUTPUT,
        16 => GPIO_V2_LINE_FLAG_EDGE_RISING,
        32 => GPIO_V2_LINE_FLAG_EDGE_FALLING,
        64 => GPIO_V2_LINE_FLAG_OPEN_DRAIN,
        128 => GPIO_V2_LINE_FLAG_OPEN_SOURCE,
        256 => GPIO_V2_LINE_FLAG_BIAS_PULL_UP,
        512 => GPIO_V2_LINE_FLAG_BIAS_PULL_DOWN,
        1024 => GPIO_V2_LINE_FLAG_BIAS_DISABLED,
        2048 => GPIO_V2_LINE_FLAG_EVENT_CLOCK_REALTIME,
        4096 => GPIO_V2_LINE_FLAG_EVENT_CLOCK_HTE,
        _ => throw ArgumentError('Unknown value for gpio_v2_line_flag: $value'),
      };
}

typedef __u64 = ffi.UnsignedLongLong;
typedef Dart__u64 = int;

/// struct gpio_v2_line_values - Values of GPIO lines
/// @bits: a bitmap containing the value of the lines, set to 1 for active
/// and 0 for inactive.
/// @mask: a bitmap identifying the lines to get or set, with each bit
/// number corresponding to the index into &struct
/// gpio_v2_line_request.offsets.
final class gpio_v2_line_values extends ffi.Struct {
  @__u64()
  external int bits;

  @__u64()
  external int mask;
}

/// enum gpio_v2_line_attr_id - &struct gpio_v2_line_attribute.id values
/// identifying which field of the attribute union is in use.
/// @GPIO_V2_LINE_ATTR_ID_FLAGS: flags field is in use
/// @GPIO_V2_LINE_ATTR_ID_OUTPUT_VALUES: values field is in use
/// @GPIO_V2_LINE_ATTR_ID_DEBOUNCE: debounce_period_us field is in use
enum gpio_v2_line_attr_id {
  GPIO_V2_LINE_ATTR_ID_FLAGS(1),
  GPIO_V2_LINE_ATTR_ID_OUTPUT_VALUES(2),
  GPIO_V2_LINE_ATTR_ID_DEBOUNCE(3);

  final int value;
  const gpio_v2_line_attr_id(this.value);

  static gpio_v2_line_attr_id fromValue(int value) => switch (value) {
        1 => GPIO_V2_LINE_ATTR_ID_FLAGS,
        2 => GPIO_V2_LINE_ATTR_ID_OUTPUT_VALUES,
        3 => GPIO_V2_LINE_ATTR_ID_DEBOUNCE,
        _ =>
          throw ArgumentError('Unknown value for gpio_v2_line_attr_id: $value'),
      };
}

final class UnnamedUnion1 extends ffi.Union {
  @__u64()
  external int flags;

  @__u64()
  external int values;

  @__u32()
  external int debounce_period_us;
}

/// struct gpio_v2_line_attribute - a configurable attribute of a line
/// @id: attribute identifier with value from &enum gpio_v2_line_attr_id
/// @padding: reserved for future use and must be zero filled
/// @flags: if id is %GPIO_V2_LINE_ATTR_ID_FLAGS, the flags for the GPIO
/// line, with values from &enum gpio_v2_line_flag, such as
/// %GPIO_V2_LINE_FLAG_ACTIVE_LOW, %GPIO_V2_LINE_FLAG_OUTPUT etc, added
/// together.  This overrides the default flags contained in the &struct
/// gpio_v2_line_config for the associated line.
/// @values: if id is %GPIO_V2_LINE_ATTR_ID_OUTPUT_VALUES, a bitmap
/// containing the values to which the lines will be set, with each bit
/// number corresponding to the index into &struct
/// gpio_v2_line_request.offsets.
/// @debounce_period_us: if id is %GPIO_V2_LINE_ATTR_ID_DEBOUNCE, the
/// desired debounce period, in microseconds
final class gpio_v2_line_attribute extends ffi.Struct {
  @__u32()
  external int id;

  @__u32()
  external int padding;

  external UnnamedUnion1 unnamed;
}

/// struct gpio_v2_line_config_attribute - a configuration attribute
/// associated with one or more of the requested lines.
/// @attr: the configurable attribute
/// @mask: a bitmap identifying the lines to which the attribute applies,
/// with each bit number corresponding to the index into &struct
/// gpio_v2_line_request.offsets.
final class gpio_v2_line_config_attribute extends ffi.Struct {
  external gpio_v2_line_attribute attr;

  @__u64()
  external int mask;
}

/// struct gpio_v2_line_config - Configuration for GPIO lines
/// @flags: flags for the GPIO lines, with values from &enum
/// gpio_v2_line_flag, such as %GPIO_V2_LINE_FLAG_ACTIVE_LOW,
/// %GPIO_V2_LINE_FLAG_OUTPUT etc, added together.  This is the default for
/// all requested lines but may be overridden for particular lines using
/// @attrs.
/// @num_attrs: the number of attributes in @attrs
/// @padding: reserved for future use and must be zero filled
/// @attrs: the configuration attributes associated with the requested
/// lines.  Any attribute should only be associated with a particular line
/// once.  If an attribute is associated with a line multiple times then the
/// first occurrence (i.e. lowest index) has precedence.
final class gpio_v2_line_config extends ffi.Struct {
  @__u64()
  external int flags;

  @__u32()
  external int num_attrs;

  /// Pad to fill implicit padding and reserve space for future use.
  @ffi.Array.multi([5])
  external ffi.Array<__u32> padding;

  @ffi.Array.multi([10])
  external ffi.Array<gpio_v2_line_config_attribute> attrs;
}

typedef __s32 = ffi.Int;
typedef Dart__s32 = int;

/// struct gpio_v2_line_request - Information about a request for GPIO lines
/// @offsets: an array of desired lines, specified by offset index for the
/// associated GPIO chip
/// @consumer: a desired consumer label for the selected GPIO lines such as
/// "my-bitbanged-relay"
/// @config: requested configuration for the lines.
/// @num_lines: number of lines requested in this request, i.e. the number
/// of valid fields in the %GPIO_V2_LINES_MAX sized arrays, set to 1 to
/// request a single line
/// @event_buffer_size: a suggested minimum number of line events that the
/// kernel should buffer.  This is only relevant if edge detection is
/// enabled in the configuration. Note that this is only a suggested value
/// and the kernel may allocate a larger buffer or cap the size of the
/// buffer. If this field is zero then the buffer size defaults to a minimum
/// of @num_lines * 16.
/// @padding: reserved for future use and must be zero filled
/// @fd: if successful this field will contain a valid anonymous file handle
/// after a %GPIO_GET_LINE_IOCTL operation, zero or negative value means
/// error
final class gpio_v2_line_request extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<__u32> offsets;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> consumer;

  external gpio_v2_line_config config;

  @__u32()
  external int num_lines;

  @__u32()
  external int event_buffer_size;

  /// Pad to fill implicit padding and reserve space for future use.
  @ffi.Array.multi([5])
  external ffi.Array<__u32> padding;

  @__s32()
  external int fd;
}

/// struct gpio_v2_line_info - Information about a certain GPIO line
/// @name: the name of this GPIO line, such as the output pin of the line on
/// the chip, a rail or a pin header name on a board, as specified by the
/// GPIO chip, may be empty (i.e. name[0] == '\0')
/// @consumer: a functional name for the consumer of this GPIO line as set
/// by whatever is using it, will be empty if there is no current user but
/// may also be empty if the consumer doesn't set this up
/// @offset: the local offset on this GPIO chip, fill this in when
/// requesting the line information from the kernel
/// @num_attrs: the number of attributes in @attrs
/// @flags: flags for this GPIO line, with values from &enum
/// gpio_v2_line_flag, such as %GPIO_V2_LINE_FLAG_ACTIVE_LOW,
/// %GPIO_V2_LINE_FLAG_OUTPUT etc, added together.
/// @attrs: the configuration attributes associated with the line
/// @padding: reserved for future use
final class gpio_v2_line_info extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> name;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> consumer;

  @__u32()
  external int offset;

  @__u32()
  external int num_attrs;

  @__u64()
  external int flags;

  @ffi.Array.multi([10])
  external ffi.Array<gpio_v2_line_attribute> attrs;

  /// Space reserved for future use.
  @ffi.Array.multi([4])
  external ffi.Array<__u32> padding;
}

/// enum gpio_v2_line_changed_type - &struct gpio_v2_line_changed.event_type
/// values
/// @GPIO_V2_LINE_CHANGED_REQUESTED: line has been requested
/// @GPIO_V2_LINE_CHANGED_RELEASED: line has been released
/// @GPIO_V2_LINE_CHANGED_CONFIG: line has been reconfigured
enum gpio_v2_line_changed_type {
  GPIO_V2_LINE_CHANGED_REQUESTED(1),
  GPIO_V2_LINE_CHANGED_RELEASED(2),
  GPIO_V2_LINE_CHANGED_CONFIG(3);

  final int value;
  const gpio_v2_line_changed_type(this.value);

  static gpio_v2_line_changed_type fromValue(int value) => switch (value) {
        1 => GPIO_V2_LINE_CHANGED_REQUESTED,
        2 => GPIO_V2_LINE_CHANGED_RELEASED,
        3 => GPIO_V2_LINE_CHANGED_CONFIG,
        _ => throw ArgumentError(
            'Unknown value for gpio_v2_line_changed_type: $value'),
      };
}

/// struct gpio_v2_line_info_changed - Information about a change in status
/// of a GPIO line
/// @info: updated line information
/// @timestamp_ns: estimate of time of status change occurrence, in nanoseconds
/// @event_type: the type of change with a value from &enum
/// gpio_v2_line_changed_type
/// @padding: reserved for future use
final class gpio_v2_line_info_changed extends ffi.Struct {
  external gpio_v2_line_info info;

  @__u64()
  external int timestamp_ns;

  @__u32()
  external int event_type;

  /// Pad struct to 64-bit boundary and reserve space for future use.
  @ffi.Array.multi([5])
  external ffi.Array<__u32> padding;
}

/// enum gpio_v2_line_event_id - &struct gpio_v2_line_event.id values
/// @GPIO_V2_LINE_EVENT_RISING_EDGE: event triggered by a rising edge
/// @GPIO_V2_LINE_EVENT_FALLING_EDGE: event triggered by a falling edge
enum gpio_v2_line_event_id {
  GPIO_V2_LINE_EVENT_RISING_EDGE(1),
  GPIO_V2_LINE_EVENT_FALLING_EDGE(2);

  final int value;
  const gpio_v2_line_event_id(this.value);

  static gpio_v2_line_event_id fromValue(int value) => switch (value) {
        1 => GPIO_V2_LINE_EVENT_RISING_EDGE,
        2 => GPIO_V2_LINE_EVENT_FALLING_EDGE,
        _ => throw ArgumentError(
            'Unknown value for gpio_v2_line_event_id: $value'),
      };
}

/// struct gpio_v2_line_event - The actual event being pushed to userspace
/// @timestamp_ns: best estimate of time of event occurrence, in nanoseconds.
/// @id: event identifier with value from &enum gpio_v2_line_event_id
/// @offset: the offset of the line that triggered the event
/// @seqno: the sequence number for this event in the sequence of events for
/// all the lines in this line request
/// @line_seqno: the sequence number for this event in the sequence of
/// events on this particular line
/// @padding: reserved for future use
///
/// By default the @timestamp_ns is read from %CLOCK_MONOTONIC and is
/// intended to allow the accurate measurement of the time between events.
/// It does not provide the wall-clock time.
///
/// If the %GPIO_V2_LINE_FLAG_EVENT_CLOCK_REALTIME flag is set then the
/// @timestamp_ns is read from %CLOCK_REALTIME.
final class gpio_v2_line_event extends ffi.Struct {
  @__u64()
  external int timestamp_ns;

  @__u32()
  external int id;

  @__u32()
  external int offset;

  @__u32()
  external int seqno;

  @__u32()
  external int line_seqno;

  /// Space reserved for future use.
  @ffi.Array.multi([6])
  external ffi.Array<__u32> padding;
}

const int GPIOLINE_CHANGED_REQUESTED = 1;

const int GPIOLINE_CHANGED_RELEASED = 2;

const int GPIOLINE_CHANGED_CONFIG = 3;

const int GPIO_MAX_NAME_SIZE = 32;

const int GPIO_V2_LINES_MAX = 64;

const int GPIO_V2_LINE_NUM_ATTRS_MAX = 10;
